substitutions:
  _IMAGE_NAME: cloud-build-demo # Configure this
  _GCS_CACHE_BUCKET: cloud-build-demo121

steps:

# load the cache from GCS if it exists
- name: gcr.io/cloud-builders/gsutil
  dir: /root
  entrypoint: bash
  args:
  - -c
  - |
    (
      gsutil cp gs://${_GCS_CACHE_BUCKET}/m2-cache.tar.gz /tmp/m2-cache.tar.gz &&
      tar -xzf /tmp/m2-cache.tar.gz
    ) || echo 'Cache not found'
  volumes:
  - name: m2
    path: /root/.m2/


- name: gcr.io/cloud-builders/docker
  id: build
  args: [ 'compile', 'jib:build', '-Dimage=gcr.io/${PROJECT_ID}/${_IMAGE_NAME}']
  volumes:
  - name: m2
    path: /root/.m2/

# cache the /root/.m2 folder and upload it to GCS bucket
- name: gcr.io/cloud-builders/gsutil
  waitFor:
  - build
  dir: /root
  entrypoint: bash
  args:
  - -c
  - |
    tar -czf /tmp/m2-cache.tar.gz .m2 &&
    gsutil cp /tmp/m2-cache.tar.gz gs://${_GCS_CACHE_BUCKET}/m2-cache.tar.gz
  volumes:
  - name: m2
    path: /root/.m2/


  
